# Generated by Django 3.0.1 on 2020-08-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPdf',
        ),
    ]
