# Generated by Django 3.0.1 on 2020-08-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
    ]
