# Generated by Django 3.0.1 on 2020-08-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0004_remove_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='product', max_length=255),
        ),
    ]
