# Generated by Django 3.0.1 on 2020-08-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0005_auto_20200808_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('photoDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Image.Photo')),
            ],
        ),
    ]
